apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-api
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: api
  template:
    metadata:
      labels:
        app: api
    spec: 
      containers:
      - name: web
        image: nginx
