Vagrant.configure("2") do |cf|
    # NFS Server
    cf.vm.provider "virtualbox" do |hv|
      hv.cpus = "2"
      hv.memory = 2048
    end
    
    cf.vm.define "nfs-server" do |nfs|
      cf.vm.box = "generic/ubuntu2004"
      cf.vm.provision "shell",path: "bootstrap_nfs.sh"
    end
 
end